expansion:
  uspto:
    - C:/Users/77936/Desktop/MetooRetro/data/uspto_model.onnx
    - C:/Users/77936/Desktop/MetooRetro/data/uspto_unique_templates.csv
  ringbreaker:
    - C:/Users/77936/Desktop/MetooRetro/data/uspto_ringbreaker_model.onnx
    - C:/Users/77936/Desktop/MetooRetro/data/uspto_ringbreaker_templates.csv.gz
  change:
    - C:/Users/77936/Desktop/MetooRetro/data/uspto_ringbreaker_model.onnx
    - C:/Users/77936/Desktop/MetooRetro/data/new_data.csv
filter:
  uspto: C:/Users/77936/Desktop/MetooRetro/data/uspto_filter_model.onnx
stock:
  zinc: C:/Users/77936/Desktop/MetooRetro/data/zinc_stock.hdf5