expansion:
  uspto:
    - \model_database\uspto_model.onnx
    - \model_database\uspto_templates.csv.gz
  ringbreaker:
    - \model_database\uspto_ringbreaker_model.onnx
    - \model_database\uspto_ringbreaker_templates.csv.gz
filter:
  uspto: \model_database\uspto_filter_model.onnx
stock:
  zinc: \model_database\zinc_stock.hdf5
